### ISSUE TITLE
forgot password not working with v1.1.0 because _user is view now

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/forgot_password#23]
```
2017-08-30 03:49:03,535 INFO  [skygear.utils.db:69][Thread-8] Reflecting database schema from postgres schema 'app_bentest20170818'.
2017-08-30 03:49:03,981 ERROR [skygear.transmitter.common:57][Thread-8] Error occurred processing request
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/skygear/utils/db.py", line 100, in get_table
    return _get_metadata().tables[_full_table_name(schema_name, name)]
KeyError: 'app_bentest20170818._user'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/skygear/transmitter/common.py", line 40, in wrapper
    return dict(result=f(self, *args, **kwargs))
  File "/usr/lib/python3.5/site-packages/skygear/transmitter/common.py", line 100, in call_func
    return self.op(obj, param.get('args', {}))
  File "/usr/lib/python3.5/site-packages/skygear/transmitter/common.py", line 174, in op
    return func(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/forgot_password/handlers/forgot_password.py", line 72, in forgot_password
    user = user_util.get_user_from_email(c, email)
  File "/usr/lib/python3.5/site-packages/forgot_password/handlers/util/user.py", line 78, in get_user_from_email
    users = get_table('_user')
  File "/usr/lib/python3.5/site-packages/skygear/utils/db.py", line 103, in get_table
    name, schema_name)
Exception: ("No table of name '{}' exists in schema '{}'.", '_user', 'app_bentest20170818')
```

**Comment by rickmak** [comment]
Updating of `_user` also cause errors.
